## Preprocessing

In [16]:
#pip install tensorflow

Collecting tensorflowNote: you may need to restart the kernel to use updated packages.

  Downloading tensorflow-2.12.0-cp39-cp39-win_amd64.whl (1.9 kB)
Collecting tensorflow-intel==2.12.0
  Downloading tensorflow_intel-2.12.0-cp39-cp39-win_amd64.whl (272.8 MB)
     ------------------------------------ 272.8/272.8 MB 134.6 kB/s eta 0:00:00
Collecting gast<=0.4.0,>=0.2.1
  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting astunparse>=1.6.0
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting flatbuffers>=2.0
  Downloading flatbuffers-23.3.3-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: setuptools in c:\users\jyoth\anaconda3\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (63.4.1)
Collecting libclang>=13.0.0
  Downloading libclang-16.0.0-py2.py3-none-win_amd64.whl (24.4 MB)
     -------------------------------------- 24.4/24.4 MB 132.2 kB/s eta 0:00:00
Requirement already satisfied: wrapt<1.15,>=1.11.0 in c:\users\jyoth\anaconda3\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (1.14.1)
Collecting grpcio<2.0,>=1.24.3
  Downloading grpcio-1.53.0-cp39-cp39-win_amd64.whl (4.0 MB)
     ---------------------------------------- 4.0/4.0 MB 185.7 kB/s eta 0:00:00
Collecting jax>=0.3.15
  Downloading jax-0.4.8.tar.gz (1.2 MB)
     ---------------------------------------- 1.2/1.2 MB 190.1 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting tensorboard<2.13,>=2.12
  Downloading tensorboard-2.12.1-py3-none-any.whl (5.6 MB)
     ---------------------------------------- 5.6/5.6 MB 144.8 kB/s eta 0:00:00
Collecting keras<2.13,>=2.12.0
  Downloading keras-2.12.0-py2.py3-none-any.whl (1.7 MB)
     ---------------------------------------- 1.7/1.7 MB 149.8 kB/s eta 0:00:00
Requirement already satisfied: h5py>=2.9.0 in c:\users\jyoth\anaconda3\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (3.7.0)
Requirement already satisfied: six>=1.12.0 in c:\users\jyoth\anaconda3\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (1.16.0)
Collecting absl-py>=1.0.0
  Downloading absl_py-1.4.0-py3-none-any.whl (126 kB)
     ------------------------------------ 126.5/126.5 kB 206.6 kB/s eta 0:00:00
Requirement already satisfied: packaging in c:\users\jyoth\anaconda3\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (21.3)
Collecting tensorflow-estimator<2.13,>=2.12.0
  Downloading tensorflow_estimator-2.12.0-py2.py3-none-any.whl (440 kB)
     ------------------------------------ 440.7/440.7 kB 134.4 kB/s eta 0:00:00
Collecting termcolor>=1.1.0
  Downloading termcolor-2.2.0-py3-none-any.whl (6.6 kB)
Collecting numpy<1.24,>=1.22
  Downloading numpy-1.23.5-cp39-cp39-win_amd64.whl (14.7 MB)
     -------------------------------------- 14.7/14.7 MB 178.3 kB/s eta 0:00:00
Collecting tensorflow-io-gcs-filesystem>=0.23.1
  Downloading tensorflow_io_gcs_filesystem-0.31.0-cp39-cp39-win_amd64.whl (1.5 MB)
     ---------------------------------------- 1.5/1.5 MB 255.3 kB/s eta 0:00:00
Collecting google-pasta>=0.1.1
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
     --------------------------------------- 57.5/57.5 kB 94.5 kB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\jyoth\anaconda3\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow) (4.3.0)
Collecting opt-einsum>=2.3.2
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     -------------------------------------- 65.5/65.5 kB 321.2 kB/s eta 0:00:00
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3
  Downloading protobuf-4.22.1-cp39-cp39-win_amd64.whl (420 kB)
     ------------------------------------ 420.6/420.6 kB 234.5 kB/s eta 0:00:00
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\jyoth\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.12.0->tensorflow) (0.37.1)
Collecting ml-dtypes>=0.0.3
  Downloading ml_dtypes-0.0.4-cp39-cp39-win_amd64.whl (97 kB)
     -------------------------------------- 98.0/98.0 kB 701.9 kB/s eta 0:00:00
Requirement already satisfied: scipy>=1.7 in c:\users\jyoth\anaconda3\lib\site-packages (from jax>=0.3.15->tensorflow-intel==2.12.0->tensorflow) (1.9.1)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\jyoth\anaconda3\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (2.0.3)
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
     ------------------------------------ 781.3/781.3 kB 226.4 kB/s eta 0:00:00
Collecting tensorboard-data-server<0.8.0,>=0.7.0
  Downloading tensorboard_data_server-0.7.0-py3-none-any.whl (2.4 kB)
Collecting google-auth-oauthlib<1.1,>=0.5
  Downloading google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Collecting google-auth<3,>=1.6.3
  Downloading google_auth-2.17.2-py2.py3-none-any.whl (178 kB)
     ------------------------------------ 178.2/178.2 kB 399.0 kB/s eta 0:00:00
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\jyoth\anaconda3\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (2.28.1)
Requirement already satisfied: markdown>=2.6.8 in c:\users\jyoth\anaconda3\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (3.3.4)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\jyoth\anaconda3\lib\site-packages (from packaging->tensorflow-intel==2.12.0->tensorflow) (3.0.9)
Collecting cachetools<6.0,>=2.0.0
  Downloading cachetools-5.3.0-py3-none-any.whl (9.3 kB)
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.9-py3-none-any.whl (34 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\jyoth\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (0.2.8)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\jyoth\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\jyoth\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (1.26.11)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jyoth\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jyoth\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (2022.9.14)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\jyoth\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow) (0.4.8)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
     ------------------------------------ 151.7/151.7 kB 210.8 kB/s eta 0:00:00
Building wheels for collected packages: jax
  Building wheel for jax (pyproject.toml): started
  Building wheel for jax (pyproject.toml): finished with status 'done'
  Created wheel for jax: filename=jax-0.4.8-py3-none-any.whl size=1439795 sha256=c8af1ada69bdd0d14956f907a6822ed1959c8d4e85fb8542dfe1e61f44ee3c68
  Stored in directory: c:\users\jyoth\appdata\local\pip\cache\wheels\05\94\dc\81042da9bced43ff430bc02043d213d9e4b210b584c39e31c1
Successfully built jax
Installing collected packages: tensorboard-plugin-wit, libclang, flatbuffers, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, rsa, protobuf, oauthlib, numpy, keras, grpcio, google-pasta, gast, cachetools, astunparse, absl-py, requests-oauthlib, opt-einsum, ml-dtypes, google-auth, jax, google-auth-oauthlib, tensorboard, tensorflow-intel, tensorflow
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.5
    Uninstalling numpy-1.21.5:
      Successfully uninstalled numpy-1.21.5
Successfully installed absl-py-1.4.0 astunparse-1.6.3 cachetools-5.3.0 flatbuffers-23.3.3 gast-0.4.0 google-auth-2.17.2 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 grpcio-1.53.0 jax-0.4.8 keras-2.12.0 libclang-16.0.0 ml-dtypes-0.0.4 numpy-1.23.5 oauthlib-3.2.2 opt-einsum-3.3.0 protobuf-4.22.1 requests-oauthlib-1.3.1 rsa-4.9 tensorboard-2.12.1 tensorboard-data-server-0.7.0 tensorboard-plugin-wit-1.8.1 tensorflow-2.12.0 tensorflow-estimator-2.12.0 tensorflow-intel-2.12.0 tensorflow-io-gcs-filesystem-0.31.0 termcolor-2.2.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
geopandas 0.9.0 requires fiona>=1.8, which is not installed.
daal4py 2021.6.0 requires daal==2021.4.0, which is not installed.
numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 1.23.5 which is incompatible.

In [11]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [12]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(columns=['EIN', 'NAME'],inplace=True)
application_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   APPLICATION_TYPE        34299 non-null  object
 1   AFFILIATION             34299 non-null  object
 2   CLASSIFICATION          34299 non-null  object
 3   USE_CASE                34299 non-null  object
 4   ORGANIZATION            34299 non-null  object
 5   STATUS                  34299 non-null  int64
 6   INCOME_AMT              34299 non-null  object
 7   SPECIAL_CONSIDERATIONS  34299 non-null  object
 8   ASK_AMT                 34299 non-null  int64
 9   IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(3), object(7)
memory usage: 2.6+ MB

In [13]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [14]:
# Look at APPLICATION_TYPE value counts for binning
application_df["APPLICATION_TYPE"].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [15]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ["T9","T13","T12","T2","T25","T14","T29","T15","T17"]

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [16]:
# Look at CLASSIFICATION value counts for binning
application_df["CLASSIFICATION"].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [17]:
# You may find it helpful to look at CLASSIFICATION alue counts >1
value_counts = application_df["CLASSIFICATION"].value_counts()
value_counts[value_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [18]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(value_counts[value_counts<300].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [19]:
# Convert categorical data to numeric with `pd.get_dummies
dummy_df = pd.get_dummies(application_df)
dummy_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [20]:
# Split our preprocessed data into our features and target arrays
y = dummy_df['IS_SUCCESSFUL'].values
X = dummy_df.drop('IS_SUCCESSFUL', axis=1)


# Split the preprocessed data into a training and testing dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [21]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [22]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 20
hidden_nodes_layer2 = 10

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))


# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 20)                900

 dense_1 (Dense)             (None, 10)                210

 dense_2 (Dense)             (None, 1)                 11

=================================================================
Total params: 1,121
Trainable params: 1,121
Non-trainable params: 0
_________________________________________________________________

In [23]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [24]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5919 - accuracy: 0.7066
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5581 - accuracy: 0.7300
Epoch 3/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5535 - accuracy: 0.7305
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5513 - accuracy: 0.7316
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5500 - accuracy: 0.7335
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7328
Epoch 7/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5477 - accuracy: 0.7336
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5469 - accuracy: 0.7341
Epoch 9/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5470 - accuracy: 0.7341
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7340
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7348
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7348
Epoch 13/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5453 - accuracy: 0.7348
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5449 - accuracy: 0.7355
Epoch 15/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5447 - accuracy: 0.7353
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5442 - accuracy: 0.7359
Epoch 17/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5444 - accuracy: 0.7343
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5440 - accuracy: 0.7354
Epoch 19/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5441 - accuracy: 0.7353
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5437 - accuracy: 0.7349
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7356
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5432 - accuracy: 0.7367
Epoch 23/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5429 - accuracy: 0.7362
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5433 - accuracy: 0.7355
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7365
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7360
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5426 - accuracy: 0.7357
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7369
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7368
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7369
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7368
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7362
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5421 - accuracy: 0.7367
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5417 - accuracy: 0.7360
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7365
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7368
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5420 - accuracy: 0.7367
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7364
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7364
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7372
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7363
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7365
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7372
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5413 - accuracy: 0.7367
Epoch 45/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5411 - accuracy: 0.7364
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7371
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5410 - accuracy: 0.7373
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7383
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7378
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7372
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7368
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7376
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5407 - accuracy: 0.7378
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7378
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7379
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7375
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7380
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7366
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.7376
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7384
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5404 - accuracy: 0.7377
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7382
Epoch 63/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5398 - accuracy: 0.7381
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5396 - accuracy: 0.7380
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7383
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7374
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7377
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7383
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5396 - accuracy: 0.7378
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7383
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7388
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7384
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7385
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7379
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5393 - accuracy: 0.7373
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5397 - accuracy: 0.7379
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7384
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7377
Epoch 79/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5391 - accuracy: 0.7387
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7388
Epoch 81/100

804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7380
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7377
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5393 - accuracy: 0.7388
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5389 - accuracy: 0.7385
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7379
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7385
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7378
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7378
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7391
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5387 - accuracy: 0.7388
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7388
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5391 - accuracy: 0.7385
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7383
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7390
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7390
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7380
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5387 - accuracy: 0.7382
Epoch 98/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5387 - accuracy: 0.7381
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7385
Epoch 100/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5382 - accuracy: 0.7381

In [26]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5527 - accuracy: 0.7275 - 560ms/epoch - 2ms/step
Loss: 0.5527288913726807, Accuracy: 0.7274635434150696

In [58]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity.h5')